# Generated by Django 5.2.2 on 2025-06-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
