# Generated by Django 5.2.2 on 2025-07-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Инвайт')),
            ],
            options={
                'verbose_name': 'Инвайт',
                'verbose_name_plural': 'Инвайты',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='invite_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Инвайт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
