# Generated by Django 5.2.2 on 2025-07-10 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activeinvites_user_invite_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinvites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 10, 11, 25, 38, 937852, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
