# Generated by Django 5.2.2 on 2025-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_activeinvites_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinvites',
            name='invite_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Инвайт URL'),
        ),
    ]
