# Generated by Django 5.2.2 on 2025-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_activeinvites_invite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeinvites',
            name='invite_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Инвайт URL'),
        ),
    ]
