# Generated by Django 5.2.2 on 2025-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_activeinvites_invite_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='old user', max_length=50, verbose_name='Инвайт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='old_user', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_number',
            field=models.CharField(default='old user', max_length=50, verbose_name='Инвайт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='old user', max_length=50, verbose_name='Фамилия'),
        ),
    ]
