# Generated by Django 5.2.2 on 2025-07-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_verification_code_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
