# Generated by Django 5.2.2 on 2025-06-26 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='first name')),
                ('customer_surname', models.CharField(max_length=50, verbose_name='last_name')),
                ('phone', models.CharField(max_length=12, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('material_type', models.CharField(max_length=35, verbose_name='материал')),
                ('box_material_thickness', models.SmallIntegerField(verbose_name='толщина')),
                ('box_material_color', models.CharField(max_length=35, verbose_name='цвет')),
                ('box_square', models.IntegerField()),
                ('box_price_per_sqm', models.IntegerField(verbose_name='цена короба за м кв')),
                ('box_price', models.IntegerField(verbose_name='цена короба')),
                ('door_type', models.CharField(max_length=35, verbose_name='тип дверей')),
                ('door_material_thickness', models.SmallIntegerField(verbose_name='толщина')),
                ('door_material_color', models.CharField(max_length=35, verbose_name='цвет')),
                ('door_square', models.IntegerField()),
                ('door_price_per_sqm', models.IntegerField(verbose_name='цена двери за м кв')),
                ('door_price', models.IntegerField(verbose_name='цена двери')),
                ('handle_name', models.CharField(max_length=35, verbose_name='тип дверной ручки')),
                ('handle_material', models.CharField(max_length=35, verbose_name='материал дверной ручки')),
                ('handle_color', models.CharField(max_length=35, verbose_name='цвет дверной ручки')),
                ('handle_length', models.CharField(max_length=35, verbose_name='длинна дверной ручки')),
                ('handle_price_per_one', models.IntegerField(verbose_name='цена дверной ручки за единицу')),
                ('handle_ammount', models.IntegerField(verbose_name='количество дверных ручек')),
                ('handle_price', models.IntegerField(verbose_name='цена дверной ручки')),
                ('total_price', models.IntegerField(verbose_name='стоимость шкафа')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='дата заказа')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
