# Generated by Django 5.2.2 on 2025-06-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='handle_length',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='длинна дверной ручки'),
        ),
    ]
