# Generated by Django 5.2.2 on 2025-07-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_alter_orders_handle_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='имя заказчика'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_surname',
            field=models.CharField(max_length=50, verbose_name='фамилия заказчика'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='телефон заказчика'),
        ),
    ]
