# Generated by Django 5.2.2 on 2025-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='furniture type')),
                ('description', models.CharField(max_length=350, verbose_name='type description')),
            ],
            options={
                'verbose_name': 'furniture',
                'verbose_name_plural': 'furniture',
            },
        ),
    ]
