# Generated by Django 5.2.2 on 2025-06-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='тип дверей')),
                ('ru_name', models.CharField(max_length=25, unique=True, verbose_name='тип дверей на русском')),
            ],
            options={
                'verbose_name': 'door type',
                'verbose_name_plural': 'door types',
            },
        ),
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='MaterialThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.SmallIntegerField(unique=True, verbose_name='толщина')),
            ],
            options={
                'verbose_name': 'thickness',
                'verbose_name_plural': 'thickness',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='материал')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
        migrations.CreateModel(
            name='DoorHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='дверная ручка')),
                ('length', models.SmallIntegerField(verbose_name='межцентровое расстояние')),
                ('material', models.CharField(max_length=25, verbose_name='материал ручки')),
                ('color', models.CharField(max_length=25, verbose_name='цвет ручки')),
                ('price_per_one', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за единицу')),
            ],
            options={
                'verbose_name': 'door handle',
                'verbose_name_plural': 'door handles',
                'unique_together': {('name', 'length', 'material', 'color')},
            },
        ),
        migrations.CreateModel(
            name='DoorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('door_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.doortype', verbose_name='тип дверей')),
                ('material_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.materialcolor', verbose_name='цвет')),
                ('material_thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.materialthickness', verbose_name='толщина')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.materialtype', verbose_name='материал')),
            ],
            options={
                'verbose_name': 'materials summary',
                'verbose_name_plural': 'materials summary',
                'unique_together': {('material_type', 'material_thickness', 'material_color', 'door_type')},
            },
        ),
        migrations.CreateModel(
            name='BoxSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.materialcolor', verbose_name='цвет')),
                ('material_thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.materialthickness', verbose_name='толщина')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.materialtype', verbose_name='материал')),
            ],
            options={
                'verbose_name': 'box materials summary',
                'verbose_name_plural': 'box materials summary',
                'unique_together': {('material_type', 'material_thickness', 'material_color')},
            },
        ),
    ]
