# Generated by Django 5.2.2 on 2025-06-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorsummary',
            options={'verbose_name': 'door summary', 'verbose_name_plural': 'door summary'},
        ),
        migrations.RemoveField(
            model_name='doortype',
            name='ru_name',
        ),
    ]
