# Generated by Django 5.2.2 on 2025-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_doorsummary_options_remove_doortype_ru_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorhandle',
            name='length',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='межцентровое расстояние'),
        ),
    ]
