# Generated by Django 5.2.2 on 2025-07-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_doorhandle_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxsummary',
            options={'verbose_name': 'Материал короба', 'verbose_name_plural': 'Материалы короба'},
        ),
        migrations.AlterModelOptions(
            name='doorsummary',
            options={'verbose_name': 'Материал дверки', 'verbose_name_plural': 'Материалы дверок'},
        ),
        migrations.AlterField(
            model_name='boxsummary',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за квадратный метр'),
        ),
        migrations.AlterField(
            model_name='doorsummary',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за квадратный метр'),
        ),
    ]
